name: Build and Release

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.feature"
      - "Kconfig"
      - ".github/workflows/build-and-release.yaml"
      - "west.yml"
      - "*.conf"
  repository_dispatch:
    types:
      - source-update
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  STACK_NAME: ${{ secrets.STACK_NAME }}
  CI: 1
  FORCE_COLOR: 3

jobs:
  # This generates a unique build id (which is also different for re-runs) to
  # be used in the artifact names to be able to distinguish them when
  # downloading the artifact files.
  build-id:
    name: Generate build ID
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id.outputs.id }}
    steps:
      - name: Generate build ID
        id: id
        run: |
          ID=`uuidgen`
          echo "::set-output name=id::${ID}"

  # This generates a string containing the current date which is used in
  # in artifact names to simpify locating and distinguishing them once they have
  # been downloaded
  date-string:
    name: Generate string containing the current date
    runs-on: ubuntu-latest
    outputs:
      dateAsString: ${{ steps.dateAsString.outputs.dateAsString }}
    steps:
      - name: Generate date string
        id: dateAsString
        run: echo "::set-output name=dateAsString::$(date +'%Y%m%d%H%M%S')"

  release-version:
    name: Determine next release version

    runs-on: ubuntu-latest

    outputs:
      nextRelease: ${{ steps.version.outputs.nextRelease }}

    steps:
      - uses: actions/checkout@v3

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga
          defaultVersion: "0.0.0-development-${{ github.sha }}"

      - run: echo ${{ steps.version.outputs.nextRelease }}

  build:
    runs-on: ubuntu-latest

    needs: [release-version, date-string]

    strategy:
      matrix:
        board: [thingy91_nrf9160_ns, nrf9160dk_nrf9160_ns]
        loglevel: [debug]
        #loglevel: [debug, nodebug]
        project: [atv2]
        #project: [atv2, mmss]
        #stage: [dev, beta, prod]
        stage: [prod]
        idtype: [imei, uuid]

    steps:
      - uses: actions/checkout@v3
        with:
          path: firmware

      - name: Create config file
        run: |
          touch firmware/firmware.conf

      - name: Set build path
        run: |
          ITEM_NAME=${{ matrix.project }}-${{ matrix.idtype }}-${{ matrix.board }}-${{ matrix.stage }}-${{ matrix.loglevel }}
          BUILD_PATH=_build/$ITEM_NAME
          echo $BUILD_PATH

      - name: Configure Version
        if: matrix.project == 'atv2'
        run: |
          APP_VERSION=${{ needs.release-version.outputs.nextRelease }}-${{ matrix.board }}-${{ matrix.loglevel }}
          echo "CONFIG_ASSET_TRACKER_V2_APP_VERSION=\"${APP_VERSION}\"" >> firmware/firmware.conf
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - name: Configure UUID Device ID
        if: matrix.idtype == 'uuid'
        run: |
          echo "CONFIG_MODEM_JWT=y" >> firmware/firmware.conf
          echo "CONFIG_NRF_CLOUD_CLIENT_ID_SRC_INTERNAL_UUID=y" >> firmware/firmware.conf

      - name: Configure MMSS Log Level
        if: matrix.loglevel == 'debug' && matrix.project == 'mmss'
        run: |
          echo "CONFIG_NRF_CLOUD_LOG_LEVEL_DBG=y" >> firmware/firmware.conf
          echo "CONFIG_MQTT_MULTI_SERVICE_LOG_LEVEL_DBG=y" >> firmware/firmware.conf

      - name: Configure ATv2 Log Level
        if: matrix.loglevel == 'debug' && matrix.project == 'atv2'
        run: |
          echo "CONFIG_NRF_CLOUD_LOG_LEVEL_DBG=y" >> firmware/firmware.conf
          echo "CONFIG_MODULES_COMMON_LOG_LEVEL_DBG=y" >> firmware/firmware.conf

      - name: Configure nRF Cloud Stage
        if: matrix.stage == 'dev' || matrix.stage == 'beta'
        run: |
          echo "CONFIG_NRF_CLOUD_HOST_NAME=\"mqtt.${{ matrix.stage }}.nrfcloud.com\"" >> firmware/firmware.conf

      - name: Display config file
        run: cat firmware/firmware.conf

      - name: Pull Docker image
        run: docker pull nordicplayground/nrfconnect-sdk:main

      - name: Build MMSS
        if: matrix.project == 'mmss'
        run: |
          docker run --rm -v ${PWD}:/workdir/project nordicplayground/nrfconnect-sdk:main \
            /bin/bash -c 'cd firmware && west init -l && west update --narrow -o=--depth=1 && \
            west build -p always -b ${{ matrix.board }} ../nrf/samples/nrf9160/nrf_cloud_mqtt_multi_service \
            -d ./$BUILD_PATH \
            -- -DOVERLAY_CONFIG="/workdir/project/firmware/firmware.conf"'

      - name: Build ATv2
        if: matrix.project == 'atv2'
        run: |
          docker run --rm -v ${PWD}:/workdir/project nordicplayground/nrfconnect-sdk:main \
            /bin/bash -c 'cd firmware && west init -l && west update --narrow -o=--depth=1 && \
            west build -p always -b ${{ matrix.board }} ../nrf/applications/asset_tracker_v2 \
            -d ./$BUILD_PATH \
            -- -DOVERLAY_CONFIG="/workdir/project/firmware/firmware.conf"'

      - name: Copy firmware
        run: |
          cp firmware/$BUILD_PATH/zephyr/merged.hex ./
          cp firmware/$BUILD_PATH/zephyr/app_signed.hex ./
          cp firmware/$BUILD_PATH/zephyr/app_update.bin ./
          cp firmware/$BUILD_PATH/zephyr/zephyr.elf ./
          cp firmware/firmware.conf ./
          rm firmware/firmware.conf

      - uses: actions/upload-artifact@v3
        with:
          name:
            ${{ matrix.project }}-${{ matrix.idtype }}-${{ matrix.board }}-${{ matrix.stage }}-${{ matrix.loglevel }}-${{needs.date-string.outputs.dateAsString }}-${{ github.sha }}
          path: |
            merged.hex
            app_signed.hex
            app_update.bin
            firmware.conf
            zephyr.elf

  release:
    name: Release
    runs-on: ubuntu-latest
    if:
      github.ref == 'refs/heads/saga' && (github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' || github.event_name ==
      'repository_dispatch')

    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - run: npx semantic-release
