name: Build and Release

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.feature"
      - "Kconfig"
      - ".github/workflows/build-and-release.yaml"
      - "west.yml"
      - "*.conf"
  repository_dispatch:
    types:
      - source-update
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  STACK_NAME: ${{ secrets.STACK_NAME }}
  CI: 1
  FORCE_COLOR: 3

jobs:
  # This generates a unique build id (which is also different for re-runs) to
  # be used in the artifact names to be able to distinguish them when
  # downloading the artifact files.
  build-id:
    name: Generate build ID
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.id.outputs.id }}
    steps:
      - name: Generate build ID
        id: id
        run: |
          ID=`uuidgen`
          echo "::set-output name=id::${ID}"

  # This generates a string containing the current date which is used in
  # in artifact names to simpify locating and distinguishing them once they have
  # been downloaded
  date-string:
    name: Generate string containing the current date
    runs-on: ubuntu-latest
    outputs:
      dateAsString: ${{ steps.dateAsString.outputs.dateAsString }}
    steps:
      - name: Generate date string
        id: dateAsString
        run: echo "::set-output name=dateAsString::$(date +'%Y%m%d%H%M%S')"

  broker:
    name: Determine broker hostname
    runs-on: ubuntu-latest
    steps:
      - name: Determine the AWS IoT broker hostname
        id: broker-hostname
        run: |
          BROKER_HOSTNAME=`AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }} AWS_DEFAULT_REGION=${{ env.AWS_REGION }} aws iot describe-endpoint --endpoint-type iot:Data-ATS | jq '.endpointAddress' -r | tr -d '\n'`
          echo ${BROKER_HOSTNAME}
          if [ -z "$BROKER_HOSTNAME" ]; then echo "Failed to discover broker hostname."; exit 1; fi
          echo ${BROKER_HOSTNAME} > broker.conf

      - uses: actions/upload-artifact@v3
        with:
          name: broker
          path: broker.conf

  release-version:
    name: Determine next release version

    runs-on: ubuntu-latest

    outputs:
      nextRelease: ${{ steps.version.outputs.nextRelease }}

    steps:
      - uses: actions/checkout@v3

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga
          defaultVersion: "0.0.0-development-${{ github.sha }}"

      - run: echo ${{ steps.version.outputs.nextRelease }}

  build:
    runs-on: ubuntu-latest

    needs: [broker, release-version, date-string]

    strategy:
      matrix:
        board: [thingy91_nrf9160_ns, nrf9160dk_nrf9160_ns]
        loglevel: [debug, nodebug]

    steps:
      - uses: actions/checkout@v3
        with:
          path: firmware

      - name: Configure Version
        run: |
          APP_VERSION=${{ needs.release-version.outputs.nextRelease }}-${{ matrix.board }}-${{ matrix.loglevel }}
          echo "CONFIG_ASSET_TRACKER_V2_APP_VERSION=\"${APP_VERSION}\"" >> firmware/firmware.conf
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: broker

      - name: Configure the AWS IoT broker hostname
        run: |
          BROKER_HOSTNAME=`cat broker.conf`
          echo "CONFIG_AWS_IOT_BROKER_HOST_NAME=\"${BROKER_HOSTNAME}\"" >> firmware/firmware.conf

      - run: cat firmware/firmware.conf

      - name: Pull Docker image
        run: docker pull nordicplayground/nrfconnect-sdk:main

      - name: Build with debug enabled
        if: matrix.loglevel == 'debug'
        run: |
          docker run --rm -v ${PWD}:/workdir/project nordicplayground/nrfconnect-sdk:main /bin/bash -c 'cd firmware && west init -l && west update --narrow -o=--depth=1 && west build -p always -b ${{ matrix.board }} ../nrf/samples/nrf9160/nrf_cloud_mqtt_multi_service'

      - name: Build with debug disabled
        if: matrix.loglevel == 'nodebug'
        run: |
          docker run --rm -v ${PWD}:/workdir/project nordicplayground/nrfconnect-sdk:main /bin/bash -c 'cd firmware && west init -l && west update --narrow -o=--depth=1 && west build -p always -b ${{ matrix.board }} ../nrf/samples/nrf9160/nrf_cloud_mqtt_multi_service'

      - name: Copy firmware
        run: |
          cp firmware/build/zephyr/merged.hex ./
          cp firmware/build/zephyr/app_signed.hex ./
          cp firmware/build/zephyr/app_update.bin ./
          cp firmware/build/zephyr/zephyr.elf ./
          cp firmware/firmware.conf ./

      - uses: actions/upload-artifact@v3
        with:
          name:
            ${{ matrix.board }}-${{ matrix.loglevel }}-${{
            needs.date-string.outputs.dateAsString }}-${{ github.sha }}
          path: |
            merged.hex
            app_signed.hex
            app_update.bin
            firmware.conf
            zephyr.elf

  release:
    name: Release
    runs-on: ubuntu-latest
    if:
      github.ref == 'refs/heads/saga' && (github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' || github.event_name ==
      'repository_dispatch')

    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - run: npx semantic-release
